# -*- coding: utf-8 -*-
"""RandomForest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_E1YdfBriR55KofHZ3Kr2ONHC6nq4rUR
"""

import pandas as pd
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier

# Load the iris dataset
iris = pd.read_csv('drive\MyDrive\IRIS-DataSet\iris.csv')
iris.drop("Id", axis = 1, inplace = True)

# Extract the feature matrix and target variable
X = iris.drop(['Species'], axis = 1)
Y = iris['Species']

# Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=5)

# Train the Random Forest classifier
model = RandomForestClassifier(criterion='gini', random_state=42)
model.fit(X_train, Y_train)

# Predict the target variable for the test set
Y_pred = model.predict(X_test)

# Evaluate the model's performance
print("Accuracy:", metrics.accuracy_score(Y_test, Y_pred)*100)
print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))
print("Classification Report:\n", classification_report(Y_test, Y_pred))